### ISSUE TITLE
Environment setup(REOPENED)

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/Team-Rio-Django#13]
### Discussed in https://github.com/SpaceyaTech/Team-Rio-Django/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **mamu234** October 31, 2022</sup>
1. install python - the latest python version in my case is 3.8
2. Install django using the following command - pip install django (this will install django without specifying the version)
3. Create a virtual environment  using the following command  - python3 -m venv env
4. Activate the virtual environment - source env /bin/activate
5. Install a list of modules needed to run the project by  - pip install -r requirements.txt
6. Check the modules that have been installed by - pip freeze</div>

**Comment by JimmyTron** [comment]
## Hold up. 
Maybe before we create the virtual environment on step 3, we should first clone the main branch of our repo locally onto our machine.
 Cd into the directory then proceed to make the virtual environment

**Comment by mamu234** [comment]
JImmy please clarify the issue for setting up that needs to be done

**Comment by LionelMv** [comment]
1. First install python3 (skip if you have it)
2. Install django using the following command: pip install django
3. Clone your repo to the location you want.
4. cd into it
5. Install the virtual environment otherwise skip: 
     sudo apt install python3.10-venv (or sudo apt install python-venv)
 6. Create the virtual environment:
    - python3 -m venv env (env is the name of your virtual environment)
    or mkdir env -> cd env -> venv -p python3
7. cd env
8. source bin/activate (to deactivate run deactivate)
9. Install a list of modules needed to run the project by - pip install -r requirements.txt (file found in Team-Rio-Django repo)
10. pip freeze to confirm the requirements are installed.
11. Create a folder in your virtual environment and start project:
	- mkdir src (can be any name)
	- cd src
	- django-admin startproject teamrio . (The dot means in the src folder. Otherwise it will create another folder inside teamrio folder called teamrio. teamrio can be any name you decide for your project).
	- python manage.py runserver (you will see the address. Click on it to redirect you to the webpage to show you have started the project successfully).

I hope this helps!

**Comment by JosephThuku** [comment]
after setting up the enviroment i think there is no need open a pull request since there are no changes

**Comment by mamu234** [comment]
Thanks LionelMv i got it !
